### ISSUE TITLE
nchan inspiration

### ISSUE THREAD

**Issue by copiousfreetime** [evanphx/eventd-rfc#5]
There may be some items from https://nchan.slact.net/ that are worth thinking of. In particular, if you are leaning towards an HTTP/1 or HTTP/2 transport layer it may be worth looking at how nchan does messaging over HTTP.

**Comment by evanphx** [comment]
Excellent! I shall.

**Comment by evanphx** [comment]
nchan looks unrelated. It's mostly just an pub/sub bus that uses URIs for addressing. There is no encoding on the messages in any form.
