### ISSUE TITLE
Protocol thoughts - *MQ*?

### ISSUE THREAD

**Issue by lpar** [evanphx/eventd-rfc#6]
How about leveraging one of the messaging protocols like MQTT or AMQP? Ultimately logging seems to me to be a special case of messaging where you store the messages in a database. Facilities are like channels/topics, and many of the desirable features are the same:
- Low protocol overhead on network
- Low CPU required to process messages
- Minimal admin required
- Resilient to temporary network disruption
- QoS / prioritization supported
- Flexible data formats allowed
- Confirmation of receipt possible

Ideally it would also be possible to have a mesh topology with exactly-once delivery, for clouds.

**Comment by evanphx** [comment]
While a queueing technology can certainly power a log receiver, any spec should not mandate one. Doing so would likely doom the spec from being widely implemented, which is one of the state goals.

**Comment by lpar** [comment]
I must be missing something. You stated a goal to "Establish a standard transport for log/event data", how are you going to do that without mandating a particular transport protocol?

**Comment by evanphx** [comment]
@lpar Good point, I wasn't being clear. AMQP and MQTT are certainly standardized (sort of) protocols but they mandate pretty heavily how a server is implemented and architected. In other words, I feel like they're not generic enough.

**Comment by lpar** [comment]
Ah, fair enough. I haven't delved into them in any depth, they've just been on my huge list of "Things to investigate when bored".
